# Q1

In [5]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f'NumPy Array:\n{arr}')

l = arr.tolist()
print (l)

NumPy Array:
[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


# Q2

In [20]:
import numpy as np
array=np.random.randint(0, 10, size=(5,5))
print(array)
s=0
for i in range(5):
    s+=array[i,i]
print(s)

[[3 8 1 7 6]
 [5 5 2 1 2]
 [9 8 6 3 8]
 [1 2 0 6 7]
 [9 2 6 2 6]]
26


# Q3


In [5]:
import numpy as np
a=np.array([[1,2],[3,5]])
l=[]
x=int(input('x:'))
for i in range(0,2):
    for j in range(0,2):
        if a[i,j]>x:
            t=a[i,j]
            l.append(t)
print(l)


x:2
[3, 5]


# Q4

In [20]:
import numpy as np
a=np.random.randint(0, 11, size=(5,5))
b=np.random.randint(0, 11, size=(5,5))
c=[]
for i in range (len(a)):
    for j in range(len(a)):
        c.append(a[i,j]+b[i,j])
print(c)

[15, 9, 6, 8, 6, 1, 4, 17, 12, 9, 7, 8, 15, 8, 16, 7, 10, 12, 19, 10, 13, 5, 10, 7, 8]


# Q5

In [9]:
import numpy as np
a=np.random.randint(0,10, size=(3,3))
l=[]
j=0
for i in range (0,len(a)):
    t=a[i,j]-a[i,j+1]-a[i,j+2]
    l.append(t)
print(a)
print(l)
        

[[7 7 5]
 [2 1 9]
 [5 5 4]]
[-5, -8, -4]
